#pragma once

enum ResourceMeshID
{
	RESOURCE_MESH_ID_UNDEFINED	= 0,
	RESOURCE_MESH_ID_CRATE		= 1,
	RESOURCE_MESH_ID_PLAYER		= 2,
	RESOURCE_MESH_ID_WALL		= 3,
	RESOURCE_MESH_ID_FULLSCREEN	= 4,
	RESOURCE_MESH_ID_GRASS		= 5,

	/* Don't add any ID after this line */

	RESOURCE_MESH_COUNT
};


enum ResourceAnimationID
{
	RESOURCE_ANIMATION_ID_UNDEFINED,
	RESOURCE_ANIMATION_ID_BIRD,
	RESOURCE_ANIMATION_ID_SOLDIER,

	/* Don't add any ID after this line */

	RESOURCE_ANIMATION_COUNT
};


enum ResourceTextureID
{
	RESOURCE_TEXTURE_ID_UNDEFINED		= 0,
	RESOURCE_TEXTURE_ID_PLAYER			= 1,
	RESOURCE_TEXTURE_ID_GAME			= 2,
	RESOURCE_TEXTURE_ID_ZOMBIE			= 3,
	RESOURCE_TEXTURE_ID_MOUNTAIN		= 4,
	RESOURCE_TEXTURE_ID_CRATE			= 5,
	RESOURCE_TEXTURE_ID_WALL			= 6,
	RESOURCE_TEXTURE_ID_BIRD			= 7,
	RESOURCE_TEXTURE_ID_SPLASHSCREEN	= 8,
	RESOURCE_TEXTURE_ID_MAINMENU		= 9,
	RESOURCE_TEXTURE_ID_SOLDIER			= 10,
	RESOURCE_TEXTURE_ID_BACKGROUND		= 11,
	RESOURCE_TEXTURE_ID_GRASS			= 12,

	/* Don't add any ID after this line */

	RESOURCE_TEXTURE_COUNT
};