#ifndef INPUT_HANDLE_LAYERS
#define INPUT_HANDLE_LAYERS

enum InputHandleProfile
{
    INPUT_HANDLE_PROFILE_NONE,
    INPUT_HANDLE_PROFILE_MENU,
	INPUT_HANDLE_PROFILE_GAMEOBJECT,
	INPUT_HANDLE_PROFILE_LEVEL
};

#endif